# We can't remove volumes in a compose override, for the test configuration using the final containers
# we don't want the volumes so this is the default override file to add the volumes in the dev case
# any override will need to include these volumes to use them.
# see:  https://github.com/docker/compose/issues/3729
---
version: "3.8"
services:
  nautobot:
    command: "nautobot-server runserver 0.0.0.0:8080"
    volumes:
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../:/source"
  docs:
    entrypoint: "mkdocs serve -v -a 0.0.0.0:8080"
    ports:
      - "8001:8080"
    volumes:
      - "../:/source"
    image: "nautobot-chatops-plugin/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
    healthcheck:
      disable: true
    tty: true
  worker:
    volumes:
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../:/source"
  mattermost:
    image: mattermost/mattermost-preview
    hostname: mattermost
    environment:
      MM_SERVICESETTINGS_ALLOWEDUNTRUSTEDINTERNALCONNECTIONS: "0.0.0.0/0"
      MM_SERVICESETTINGS_ENABLEDEVELOPER: "true"
      MM_SERVICESETTINGS_SITEURL: "http://mattermost:8065"
      MM_TEAMSETTINGS_ENABLEOPENSERVER: "true"
    ports:
      - "8065:8065"
    volumes:
      - "./mattermost/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
      - "mattermost-data:/var/lib/mysql"
      # - "../:/source"
      # - "./mattermost/config:/mm/mattermost/config"
    # extra_hosts:
    #   - "dockerhost:127.0.0.1"

volumes:
  mattermost-data:
