---
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/develop/docs"
site_dir: "nautobot_chatops/static/nautobot_chatops/docs"
site_name: "Nautobot ChatOps Documentation"
site_url: "https://docs.nautobot.com/projects/chatops/en/stable/"
repo_url: "https://github.com/nautobot/nautobot-plugin-chatops"
copyright: "Copyright &copy; 2020 Network to Code"
theme:
  name: "material"
  navigation_depth: 4
  custom_dir: "docs/assets/overrides"
  hljs_languages:
    - "django"
    - "yaml"
  features:
    - "navigation.tracking"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "search.suggest"
    - "search.highlight"
    - "search.share"
    - "navigation.indexes"
  favicon: "assets/favicon.ico"
  logo: "assets/nautobot_logo.svg"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "black"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "black"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
extra_css:
  - "assets/extra.css"

# needed for RTD version flyout menu
# jquery is not (yet) injected by RTD automatically and it might be dropped
# as a dependency in the future
extra_javascript:
  - "https://code.jquery.com/jquery-3.6.0.min.js"

extra:
  generator: false
  ntc_sponsor: true
  social:
    - icon: "fontawesome/solid/rss"
      link: "https://blog.networktocode.com/blog/tags/nautobot"
      name: "Network to Code Blog"
    - icon: "fontawesome/brands/youtube"
      link: "https://www.youtube.com/playlist?list=PLjA0bhxgryJ2Ts4GJMDA-tPzVWEncv4pb"
      name: "Nautobot Videos"
    - icon: "fontawesome/brands/slack"
      link: "https://www.networktocode.com/community/"
      name: "Network to Code Community"
    - icon: "fontawesome/brands/github"
      link: "https://github.com/nautobot/nautobot"
      name: "GitHub Repo"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/networktocode"
      name: "Network to Code Twitter"
markdown_extensions:
  - "admonition"
  - "toc":
      permalink: true
  - "attr_list"
  - "md_in_html"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"

plugins:
  - "search"
  - mkdocstrings:
      default_handler: "python"
      handlers:
        python:
          paths: ["."]
          options:
            show_root_heading: true
            show_category_heading: false

watch:
  - "README.md"

nav:
  - Overview: "index.md"
  - User Guide:
      - App Overview: "user/app_overview.md"
      - Getting Started: "user/app_getting_started.md"
      - Frequently Asked Questions: "user/app_faq.md"
  - Administrator Guide:
      - Install and Configure:
          - "admin/install/index.md"
          - "admin/install/slack_setup.md"
          - "admin/install/mattermost_setup.md"
          - "admin/install/webex_setup.md"
          - "admin/install/microsoft_teams_setup.md"
      - Upgrade: "admin/admin_upgrade.md"
      - Uninstall: "admin/admin_uninstall.md"
      - Release Notes:
          - "admin/release_notes/index.md"
          - v1.9: "admin/release_notes/version_1.9.md"
          - v1.8: "admin/release_notes/version_1.8.md"
          - v1.7: "admin/release_notes/version_1.7.md"
          - v1.6: "admin/release_notes/version_1.6.md"
          - v1.5: "admin/release_notes/version_1.5.md"
          - v1.4: "admin/release_notes/version_1.4.md"
          - v1.3: "admin/release_notes/version_1.3.md"
          - v1.2: "admin/release_notes/version_1.2.md"
          - v1.1: "admin/release_notes/version_1.1.md"
  - Developer Guide:
      - Extending the App: "dev/dev_extending.md"
      - Contributing to the App: "dev/dev_contributing.md"
      - Design Documentation: "dev/design.md"
      - Development Environment: "dev/dev_environment.md"
      - Code Reference:
          - "dev/code_reference/index.md"
          - Models: "dev/code_reference/models.md"
          - API: "dev/code_reference/api.md"
          - Dispatchers:
              - "dev/code_reference/base.md"
              - "dev/code_reference/slack.md"
              - "dev/code_reference/webex.md"
              - "dev/code_reference/ms_teams.md"
              - "dev/code_reference/mattermost.md"
  - Nautobot Docs Home ↗︎: "https://docs.nautobot.com"
