[tool.poetry]
name = "nautobot-chatops"
version = "1.3.1"
description = "A plugin providing chatbot capabilities for Nautobot"
authors = ["Network to Code, LLC <opensource@networktocode.com>"]
readme = "README.md"
homepage = "https://github.com/nautobot/nautobot-plugin-chatops"
repository = "https://github.com/nautobot/nautobot-plugin-chatops"
keywords = ["nautobot", "nautobot-plugin"]
include = [
    "LICENSE",
    "README.md",
]

[tool.poetry.plugins."nautobot.workers"]
"clear" = "nautobot_chatops.workers.clear:clear"
"nautobot" = "nautobot_chatops.workers.nautobot:nautobot"

[tool.poetry.dependencies]
python = "^3.6"
nautobot = "^1.0.0"
nautobot-capacity-metrics = "*"
texttable = "^1.6.2"
PyJWT = "^2.1.0"
webexteamssdk = "^1.3"
slack-sdk = "^3.4.2"

[tool.poetry.dev-dependencies]
black = "*"
yamllint = "*"
bandit = "*"
pylint = "*"
pylint-django = "*"
pydocstyle = "*"
prybar = "*"
invoke = "*"
flake8 = "*"

[tool.black]
line-length = 120
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | settings.py     # This is where you define files that should not be stylized by black
                     # the root of the project
)
'''

[tool.pylint.master]
# Including the pylint_django plugin
load-plugins="pylint_django"

[tool.pylint.message_control]
disable=""",
    django-not-configured,
    too-few-public-methods,
    """

[tool.pylint.miscellaneous]
notes=""",
    FIXME,
    XXX,
    """

[tool.pylint.format]
max-line-length=120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.basic]
# No docstrings required for private methods (Pylint default), or for test_ functions, or for inner Meta classes.
no-docstring-rgx="^(_|test_|Meta$)"

[tool.pylint.similarities]
min-similarity-lines=12

# Don't call it "duplicate code" just because two files have the same set of import headers
ignore-imports=true

[tool.pylint.design]
# Default setting is max-args=5
max-args=6
# Default setting is max-public-methods=20
max-public-methods=22

