[tool.poetry]
name = "nautobot-chatops"
version = "1.11.0"
description = "A plugin providing chatbot capabilities for Nautobot"
authors = ["Network to Code, LLC <opensource@networktocode.com>"]
readme = "README.md"
homepage = "https://github.com/nautobot/nautobot-plugin-chatops"
repository = "https://github.com/nautobot/nautobot-plugin-chatops"
documentation = "https://docs.nautobot.com/projects/chatops/en/stable/"
keywords = ["nautobot", "nautobot-plugin"]
include = [
    "LICENSE",
    "README.md",
    # Poetry by default will exclude files that are in .gitignore
    "nautobot_chatops/static/nautobot_chatops/docs/**/*",
]

[tool.poetry.plugins."nautobot.workers"]
"clear" = "nautobot_chatops.workers.clear:clear"
"ipfabric" = "nautobot_chatops.integrations.ipfabric.worker:ipfabric"
"nautobot" = "nautobot_chatops.workers.nautobot:nautobot"
"ansible" = "nautobot_chatops.integrations.ansible.worker:ansible"

[tool.poetry.dependencies]
# TODO Move to ~ requirements instead of ^
python = "^3.7.1"
Markdown = "!=3.3.5"
PyJWT = "^2.1.0"
aiodns = "^1.0"
aiohttp = "^3.7.3"
asgiref = "^3.4.1"
nautobot = "^1.4.0"
nautobot-capacity-metrics = "*"
requests = "^2.25.1"
slack-sdk = "^3.4.2"
texttable = "^1.6.2"
webexteamssdk = "^1.3"

# Optional dependencies
PyYAML = { version = "^6.0", optional = true }
netutils = { version = "^1.0.0", optional = true }
ipfabric = { version = "~6.0.9", optional = true }
ipfabric-diagrams = { version = "~6.0.2", optional = true }

[tool.poetry.dev-dependencies]
black = "*"
yamllint = "*"
bandit = "*"
pylint = "*"
pylint-django = "*"
pydocstyle = "*"
prybar = "*"
invoke = "*"
flake8 = "^3.9.2"
# Rendering docs to HTML
mkdocs = "1.3.1"
# Material for mkdocs theme
mkdocs-material = "8.4.2"
# Automatic documentation from sources, for MkDocs
mkdocstrings = "0.19"
mkdocstrings-python = "0.7.1"
# Render custom markdown for version added/changed/remove notes
mkdocs-version-annotations = "~1.0.0"
# Allow Markdown files to include other files
mkdocs-include-markdown-plugin = "~3.6.1"
# Change log management and generation
towncrier = "~22.8.0"
coverage = "~5.4"
requests-mock = "^1.9.3"

[tool.poetry.extras]
all = [
    "PyYAML",
    "ipfabric",
    "ipfabric-diagrams",
    "netutils",
]
ansible = [
    "PyYAML",
]
ipfabric = [
    "ipfabric",
    "ipfabric-diagrams",
    "netutils",
]

[tool.black]
line-length = 120
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | settings.py     # This is where you define files that should not be stylized by black
                     # the root of the project
)
'''

[tool.pylint.master]
# Including the pylint_django plugin
load-plugins="pylint_django"

[tool.pylint.message_control]
disable=""",
    django-not-configured,
    too-few-public-methods,
    too-many-lines,
    """

[tool.pylint.miscellaneous]
notes=""",
    FIXME,
    XXX,
    """

[tool.pylint.design]
max-args=6
max-public-methods=22

[tool.pylint.similarities]
ignore-imports= true
min-similarity-lines=0

[tool.pylint.format]
max-line-length=120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.towncrier]
package = "nautobot_chatops"
directory = "changes"
filename = "docs/admin/release_notes/version_1.11.md"
template = "development/towncrier_template.j2"
start_string = "<!-- towncrier release notes start -->"
issue_format = "[#{issue}](https://github.com/nautobot/nautobot-plugin-chatops/issues/{issue})"

[tool.towncrier.fragment.added]
[tool.towncrier.fragment.changed]
[tool.towncrier.fragment.deprecated]
[tool.towncrier.fragment.fixed]
[tool.towncrier.fragment.removed]
[tool.towncrier.fragment.security]
