---
name: "Setup the environment"
description: "This action setup the Poetry environment and load virtual environment from cache if cache exists."
outputs:
  cache-used:
    description: "The property that defines if cache was used"
    value: "${{ steps.cached-poetry.outputs.cache-hit }}"
runs:
  using: "composite"
  steps:
    - name: "Set up Python"
      uses: "actions/setup-python@v2"
      id: "python-setup"
      with:
        python-version: "3.9"
    - name: "Log: Install Poetry"
      run: "echo Installing Poetry"
      shell: "bash"
    - name: "Install Poetry"
      run: "pip install poetry"
      shell: "bash"
    - name: "Log: Check cache"
      run: "echo Checking cache"
      shell: "bash"
    - name: "Cache"
      uses: "actions/cache@v2"
      id: "cached-poetry"
      with:
        path: "~/.cache/pypoetry/virtualenvs/"
        key: "{{ runner.os }}-poetry-${{ steps.python-setup.outputs.python-version }}-${{ hashFiles('./poetry.lock') }}"
    - name: "Install environment"
      run: "poetry install"
      shell: "bash"
